# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkau_app', '0002_auto_20171114_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='bkau_app.Author'),
        ),
    ]
