# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkau_app', '0003_auto_20171114_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='bkau_app.Book'),
        ),
    ]
